language: node_js
node_js:
  - 0.10
# android-17 is required because when checking out the cordova-android 3.0.0, the target is android-17
env:
  matrix:
    - ANDROID_SDKS=android-18,android-17 ANDROID_TARGET=android-18 SYS_IMG=sysimg-18
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
  - tar -xvzf android-sdk_r22.2.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0
  - echo y | android update sdk -u -a -t 1,2,3,4,5,6,7,extra-android-support,$ANDROID_SDKS,$SYS_IMG > /dev/null
#install:  - cd example
before_script:
  - npm install -g grunt-cli
  - npm install
script: grunt